# Generated by Django 3.2 on 2024-12-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_remove_usuario_ingresos_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default=12841827, max_length=10),
        ),
    ]
