# Generated by Django 3.2 on 2024-12-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0004_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
