# Generated by Django 3.2 on 2024-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vendedora',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Propietaria',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
