# Generated by Django 3.2 on 2024-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_vendedora'),
        ('usuarios', '0002_auto_20241127_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendedora',
        ),
    ]
