# Generated by Django 3.2 on 2024-12-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20241219_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
